version: "3.6"

services:
  cars_db:
    image: "postgres"
    env_file:
      - env.postgres
    volumes:
    - database-data:/var/lib/postgresql/data/

  django:
    build: .
    image: "django"
    command: /start
    restart: always
    volumes:
    - .:/code
    ports:
    - "8089:8089"
    depends_on:
      - cars_db


volumes:
  database-data: